# Qualidade e preparação dos dados

## Objetivo

Avaliar a qualidade dos dados fornecidos, identificar inconsistências e preparar uma base confiável para análise.

## Estrutura do notebook

1. Importação das bibliotecas
2. Leitura dos dados da camada Bronze
3. Conhecimento inicial das bases
4. Identificação de inconsistências
5. Tratamento dos dados
6. Validação e salvamento na camada Silver

In [9]:
import pandas as pd

ativos = pd.read_csv('../data/bronze/ativos.csv', sep=';')
vulnerabilidades = pd.read_csv('../data/bronze/vulnerabilidades.csv', sep=';')

In [10]:
ativos.head()

,ativo_id,sistema,criticidade,dominio,ambiente,localidade,status_ativo
0,A0001,Sistema_1,Crítica,Dominio_2,Homologação,São Paulo,Em desativação
1,A0002,Sistema_2,Média,Dominio_3,Produção,São Paulo,Em desativação
2,A0003,Sistema_3,Média,Dominio_4,Homologação,São Paulo,Ativo
3,A0004,Sistema_4,Alta,Dominio_5,Homologação,Campinas,Ativo
4,A0005,Sistema_5,Alta,Dominio_6,Produção,Recife,Ativo

In [11]:
vulnerabilidades.head()

,vuln_id,ativo_id,severidade,origem,data_abertura,data_correcao,status,cvss_score
0,V00001,A0078,Baixa,Cloud Security,21/03/2026,NaN,Em tratamento,2.8
1,V00002,A0060,Alta,Qualys,01/06/2026,NaN,Em tratamento,7.5
2,V00003,A0080,Alta,Veracode,18/08/2026,NaN,Aberta,1.7
3,V00004,A0086,Alta,Qualys,16/06/2026,NaN,Aberta,2.5
4,V00005,A0089,Alta,Cloud Security,12/02/2026,NaN,Em tratamento,4.4